eureka:
  client:
    service-url:
      defaultZone: ${hostname:localhost}:8761/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: xoxoEureka
server:
  port: 8761