
spring:
  application:
    name: product-server
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        auto-commit: true
        connection-test-query: SELECT 1
        connection-timeout: 30000
        idle-timeout: 30000
        max-lifetime: 1765000
        maximum-pool-size: 15
        minimum-idle: 5
        pool-name: DatebookHikariCP
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://192.168.138.223:3306/cloudall?zeroDateTimeBehavior=convertToNull&autoReconnect=true&autoReconnectForPools=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://47.105.162.64:5006/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      field-strategy: not_null
      id-type: id_worker
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
    refresh-mapper: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xoxo.product.model
server:
  port: 8081
