spring:
  application:
    name: kafka-server
  cloud:
    stream:
      bindings:
        #配置自己定义的通道与哪个中间件交互
        shop_input_group1: #ShopChannel里Input和Output的值
          binder: kafka1
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          group: cloud-shop_group1
          content-type: application/json
          destination: shop_topic #目标主题
        #配置自己定义的通道与哪个中间件交互
        shop_input_group2: #ShopChannel里Input和Output的值
          binder: kafka1
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          group: cloud-shop_group2
          content-type: application/json
          destination: shop_topic #目标主题
        shop_output:
          binder: kafka1
          consumer:
            headerMode: raw
          producer:
            headerMode: raw
          content-type: application/json
          destination: shop_topic
      default-binder: kafka #默认的binder是kafka
      binders:
        kafka1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: 192.168.138.223:9092
server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: localhost
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug

